# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  # Pods for IonicRunner
  pod 'FirebaseMessaging', '~> 11'
  capacitor_pods
end

target 'PluginTests' do
  pod 'FirebaseMessaging', '~> 11'
  capacitor_pods
end
