# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Plugin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IonicRunner

  #pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Capacitor', :path => '/Users/stewan/dev/capacitor'
  # pod 'Capacitor' ## uncomment to use capacitor's in production version
end

target 'PluginTests' do
  use_frameworks!

  #pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Capacitor', :path => '/Users/stewan/dev/capacitor'
  # pod 'Capacitor' ## uncomment to use capacitor's in production version
end
